### ISSUE TITLE
changing nick does not change how a user sees their timestamp

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#18]

**Comment by pkobrien** [comment]
Yeah, it did when I refreshed my browser, but we don't want the user to have to refresh. Not a big deal, but definitely needs fixing.

**Comment by jamesnvc** [comment]
Yes, mentions/nicknames were very recently added; it should be a very small change to fix this.

**Comment by jamesnvc** [comment]
Hm, so https://github.com/braidchat/braid/commit/e8acf059d363003051e3ea45320f35b900812f10 pushes the change to the client, but existing threads don't get re-rendered, due to how we're kinda abusing the state.  Switching to om.next would probably fix this (as the problem is that the thread needs to a reference to both the message & the sender, but only has a cursor for the message).  At least now new messages from the user will show updated nicknames.

**Comment by rafd** [comment]
good enough for now, we'll keep this issue open, but not high prio

**Comment by rafd** [comment]
fixed by https://github.com/braidchat/braid/commit/581f41b236fc88af9a9ced3f20b3c98f8c1ef4f4
