### ISSUE TITLE
indicate who is online in a group

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#24]

**Comment by pkobrien** [comment]
and I want to flag people in different ways so that, for example, @rafd would be higher in that list if I was waiting for him to come online so that I had a better chance of conversing in real-time rather than async. Or maybe not. Maybe there are other ways to tackle this. This is just what I do on Slack.

**Comment by pkobrien** [comment]
real-time vs async are going to be interesting things to play with in braid

**Comment by jamesnvc** [comment]
Indeed, the async is something I think is very important to how braid works and I want to make sure that doesn't get lost

**Comment by pkobrien** [comment]
I agree. The clean slate and async without FOMO is refreshing and feels healthier.

**Comment by rafd** [comment]
FOMO is a good observation, added it to https://github.com/braidchat/braid/wiki/Motivation

**Comment by rafd** [comment]
https://github.com/braidchat/braid/commit/1cc209959c6fb08f4ea81e251357611ac41b7432
