### ISSUE TITLE
larger avatars

### ISSUE THREAD

**Issue by rafd** [braidchat/meta#32]

**Comment by pkobrien** [comment]
Yeah, I have a hard time seeing the tiny ones now, so I can't recognize who I am chatting with, and that is just a big problem because I chat completely differently depending on who I am addressing. So, really, the main issue isn't just the size of the avatar but the ability to immediately identify the speaker.

**Comment by rafd** [comment]
https://github.com/braidchat/braid/commit/2d94f0dc6d8b391ba87dc0060fe318ea19b04e7d fixed

**Comment by pkobrien** [comment]
:metal:
